config/routes.rb
Bookstore::Application.routes.draw do

  get "dashboard/index"

  as :user do
    get "/login", :to => "authentication/sessions#new", as: :new_user_session
    delete "/logout", :to => "authentication/sessions#new", as: :destroy_user_session
    match "/signup", :to => "authentication/registrations#new", as: :new_user_registration
    match "/settings/profile", :to => "authentication/registrations#edit", as: :edit_user_registration
  end

  scope ":login", :as => :user do
  end

  devise_for :users, { :controllers => {:registrations => "authentication/registrations", :sessions => "authentication/sessions", :passwords => "authentication/passwords"}}

  match 'dashboard' => 'dashboard#index', as: :user_root                                                                                                           


  namespace :api do
    namespace :v1 do
      resources :books
      resources :reading_lists
    end
  end
  
  resources :reading_lists

  root :to => "reading_lists#index"

  # Sample of regular route:
  #   match 'products/:id' => 'catalog#view'
  # Keep in mind you can assign values other than :controller and :action

  # Sample of named route:
  #   match 'products/:id/purchase' => 'catalog#purchase', :as => :purchase
  # This route can be invoked with purchase_url(:id => product.id)

  # Sample resource route (maps HTTP verbs to controller actions automatically):
  #   resources :products

  # Sample resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Sample resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Sample resource route with more complex sub-resources
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', :on => :collection
  #     end
  #   end

  # Sample resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end

  # You can have the root of your site routed with "root"
  # just remember to delete public/index.html.
  # root :to => 'welcome#index'

  # See how all your routes lay out with "rake routes"

  # This is a legacy wild controller route that's not recommended for RESTful applications.
  # Note: This route will make all actions in every controller accessible via GET requests.
  # match ':controller(/:action(/:id))(.:format)'
end

app/models/book.rb
class Book < ActiveRecord::Base

  belongs_to :reading_list

  attr_accessible :author, :title, :publisher

  
end

app/models/publisher.rb
class Publisher < ActiveRecord::Base

  has_many :employees, :class_name => User, as: :organization

  def self.prototype(attrs)
    publisher = self.new
    publisher.name = attrs[:name]
    publisher
  end


end

app/models/reading_list.rb
class ReadingList < ActiveRecord::Base

  has_many :books

  scope :without_current, lambda{|reading_list| where("id != ?", reading_list.id)} 

  attr_accessible :description, :end, :name, :start
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  attr_accessible :first_name, :last_name, :login

  belongs_to :organization, :polymorphic => true

  def self.prototype
    user = self.new
    user.first_name = "Peter"
    user.last_name = "Miller"
    user.email = "peter@tester.com"
    user.password = "test123"
    user
  end

  def to_param
    login
  end
end

app/controllers/api/v1/base_controller.rb
class Api::V1::BaseController < ActionController::Base
  respond_to :json
end

app/controllers/api/v1/books_controller.rb
class Api::V1::BooksController < Api::V1::BaseController

  respond_to :json, :csv

  def index
    @books = exhibit(Book.all, self)
    respond_with(@books)
  end

end

app/controllers/api/v1/reading_lists_controller.rb
class Api::V1::ReadingListsController < Api::V1::BaseController

  respond_to :json, :csv

  def show
    @books = exhibit(ReadingList.find(params[:id]), self)
    respond_with(@books)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  include DisplayCase::ExhibitsHelper

  before_filter :assign_current_user

  def assign_current_user
    @current_user = exhibit(current_user)
  end
end

app/controllers/authentication/registrations_controller.rb
class Authentication::RegistrationsController < Devise::RegistrationsController

  respond_to :html
  append_view_path 'app/views/authentication'

  def edit
    1
  end


end

app/controllers/authentication/sessions_controller.rb
class Authentication::SessionsController < Devise::SessionsController

  respond_to :html
  append_view_path 'app/views/authentication'


end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  def index
  end
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController

  respond_to :html
  
  def index
    @books = exhibit(Book.all)
    @reading_lists = exhibit(ReadingList.all)
    respond_with(@reading_lists, @books)
  end

end

app/controllers/reading_lists_controller.rb
class ReadingListsController < ApplicationController 

  respond_to :html

  def show
    @reading_list = exhibit(ReadingList.find(params[:id]), self)
    respond_with(@reading_list)
  end

  def index
    @books = exhibit(Book.all)
    @reading_lists = exhibit(ReadingList.all)
    respond_with(@reading_lists, @books)
  end

end

app/controllers/users.rb
module Users
end

app/helpers/application_helper.rb
module ApplicationHelper
  def exhibit(construct, context)
    DisplayCase::ExhibitsHelper.exhibit(construct, context)
  end
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/views/authentication/shared/_links.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Sign in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{provider.to_s.titleize}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>

app/views/books/index.html.erb
<h1>Books#index</h1>
<p>Find me in app/views/books/index.html.erb</p>

app/views/dashboard/index.html.erb
<h1>User Dashboard</h1>

   <div class="span2 well">
      My Reading Lists:
      <% @reading_lists.each do |e| %>
        <%= e.render_overview(self) %>
      <% end %>
   </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Bookstore</title>
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<div class="navbar">
  <div class="navbar-inner">
     <%= @current_user.render_navigation_profile(self) %>
  </div>
</div>

<div class="container-fluid">
  <%= yield %>
</div>

</body>
</html>

app/views/reading_list/_form.html.erb
<%= form_for @reading_list, :html => { :class => 'form-horizontal' } do |f| %>
  <div class="control-group">
    <%= f.label :name, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :name, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :start, :class => 'control-label' %>
    <div class="controls">
      <%= f.date_select :start, :class => 'date_select' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :end, :class => 'control-label' %>
    <div class="controls">
      <%= f.date_select :end, :class => 'date_select' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :description, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_area :description, :class => 'text_area' %>
    </div>
  </div>

  <div class="form-actions">
    <%= f.submit nil, :class => 'btn btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                reading_list_path, :class => 'btn' %>
  </div>
<% end %>

app/views/reading_list/edit.html.erb
<%- model_class = @reading_list.class -%>
<div class="page-header">
  <h1><%=t '.title', :default => t('helpers.titles.edit', :model => model_class.model_name.human,
                                   :default => "Edit #{model_class.model_name.human}") %></h1>
</div>
<%= render :partial => 'form' %>

app/views/reading_list/index.html.erb
<%- model_class = ReadingList.new.class -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:name) %></th>
      <th><%= model_class.human_attribute_name(:start) %></th>
      <th><%= model_class.human_attribute_name(:end) %></th>
      <th><%= model_class.human_attribute_name(:description) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @reading_lists.each do |reading_list| %>
      <tr>
        <td><%= link_to reading_list.id, reading_list_path(reading_list) %></td>
        <td><%= reading_list.name %></td>
        <td><%= reading_list.start %></td>
        <td><%= reading_list.end %></td>
        <td><%= reading_list.description %></td>
        <td><%=l reading_list.created_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_reading_list_path(reading_list), :class => 'btn btn-mini' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      reading_list_path(reading_list),
                      :method => :delete,
                      :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')),
                      :class => 'btn btn-mini btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_reading_list_path,
            :class => 'btn btn-primary' %>

app/views/reading_list/new.html.erb
<%- model_class = @reading_list.class -%>
<div class="page-header">
  <h1><%=t '.title', :default => t('helpers.titles.new', :model => model_class.model_name.human,
                                 :default => "New #{model_class.model_name.human}") %></h1>
</div>
<%= render :partial => 'form' %>

app/views/reading_list/show.html.erb
<%- model_class = @reading_list.class -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:name) %>:</strong></dt>
  <dd><%= @reading_list.name %></dd>
  <dt><strong><%= model_class.human_attribute_name(:start) %>:</strong></dt>
  <dd><%= @reading_list.start %></dd>
  <dt><strong><%= model_class.human_attribute_name(:end) %>:</strong></dt>
  <dd><%= @reading_list.end %></dd>
  <dt><strong><%= model_class.human_attribute_name(:description) %>:</strong></dt>
  <dd><%= @reading_list.description %></dd>
</dl>

<div class="form-actions">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              reading_list_path, :class => 'btn'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_reading_list_path(@reading_list), :class => 'btn' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              reading_list_path(@reading_list),
              :method => 'delete',
              :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')),
              :class => 'btn btn-danger' %>
</div>

app/views/reading_lists/index.html.erb
<div class="row-fluid">
  <div class="span8">
    <% @books.each do |book| %>
      <%= book.render_book(self) %>
    <% end %>
   </div>

   <div class="span2 well">
      Suggested Reading Lists:
      <% @reading_lists.each do |e| %>
        <%= e.render_overview(self) %>
      <% end %>
   </div>
</div>

app/views/reading_lists/show.html.erb
<div class="row-fluid">
  <div class="span8">
      <h2>Reading List Suggestion - "<%= @reading_list.name %>"</h2>
      <%= @reading_list.render_books(self) %>
   </div>

   <div class="span2 well">
      <%= @reading_list.render_navigation(self) %>
   </div>
</div>

app/views/shared/_book.html.erb
<div class="book">
  <h3> Book Title: <%= book.title %> </h3>
  by <%= book.author %> (published at <%= book.publisher %>)
</div>

app/views/shared/_reading_list.html.erb
<h5> <%= link_to reading_list.name, reading_list_path(reading_list.id) %></h5>
<div class="details">
  <div class="reading-list-size">
    Number of books: <%= reading_list.books.size %>
  </div>
  <div class="reading-list-authors">
    Authors: <%= reading_list.books.map { |book| book.author }.uniq.to_s %>
  </div>
  <div class="reading-list-publishers">
    Publishers: <%= reading_list.books.map { |book| book.publisher }.uniq.to_s %>
  </div>
</div>

app/views/shared/_reading_list_navigation.html.erb
<ul>
  <h5>
    Selected Reading List:
    <%= selected_reading_list %>
  </h5>
  <li>
    Alternative reading lists:
  </li>
  <% other_reading_lists.each do |reading_list| %>
    <li>
      <%= link_to reading_list.name, reading_list_path(reading_list.id) %>
    </li>
  <% end %>
  <li>
    <%= link_to "Back to overview", root_path %> 
  </li>
</ul>

app/views/shared/_signedin.html.erb
    <div class="container">
        <%= link_to "Bookstore", user_root_path, :class => "brand" %>
      <ul class="nav pull-right">
         <li>
            <%= link_to "My profile", edit_user_registration_path %> 
         </li>
         <li>
           <%= link_to "Logout", destroy_user_session_path, :method => :delete %>
         </li>
      </ul>
    </div>

app/views/shared/_signup.html.erb
    <div class="container">
        <%= link_to "Bookstore", root_path, :class => "brand" %>
      <ul class="nav pull-right">
         <li>
           <%= link_to "Sign up", new_user_registration_path %>
         </li>
         <li>
           <%= link_to "Sign in", new_user_session_path %>
         </li>
      </ul>
    </div>